version: "3.9"
services:
  webapi:
    image: minishop:v1
    container_name: minishop
    ports:
      - "3000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    platform: linux/amd64
    container_name: sql_server2022_minishop
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=${SA_PASSWORD}